#define NFND       "HTTP/1.0 404 Not Found\r\n"
#define BRQ        "HTTP/1.0 400 Bad Request\r\n"
#define MSG404     "<html><body><h1>FILE NOT FOUND</h1></body></html>"
#define MSG400     "<html><body><h1>REQUEST NOT SUPPORTED/BAD REQUEST</h1></body></html>"
#define RSPOK      "HTTP/1.0 200 OK\r\n"
#define TXT        "Content-Type: text/html\n"
#define GIF        "Content-Type: image/gif\n"
#define LIST       "<html>List of Files<br>"
#define TEXT       "Content-Type: text/html\r\nContent-Length: 50\r\n\r\n"
#define SERVER     "Server: SWEB/2.3.1\n"

